### ISSUE TITLE
Allow continuous variable as PHE

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/gel-gwas#39]
https://github.com/lifebit-ai/gel-gwas/blob/a13eb4eb85930d9ecd6db42053cc4763fe54e792/main.nf#L255

```
# quantitative
--traitType=quantitative
--invNormalize=TRUE	
```

```
# binary
--traitType=binary
```

**Comment by mcamarad** [comment]
@cgpu When you test for missingness in a GWAS is it possible to do it when you have a quantitative trait? I was trying the pipeline with qt traits and couldn't make it work because the option seems to be only for case/control ones.
Found this on the ref: https://www.cog-genomics.org/plink/1.9/assoc#test_missing
12:45

This issue affects this part of the code: https://github.com/lifebit-ai/gel-gwas/blob/a84f43f084be986c9b3d7b0b1587902bb69b7f38/main.nf#L198-L208

So far, I've decided to create a switch and remove the missingness part from the qt processes which seems to work fine with qt now.

**Comment by cgpu** [comment]
> So far, I've decided to create a switch and remove the missingness part from the qt processes which seems to work fine with qt now.

For 1st iter should be good, as discussed earlier having the test with a file that has NAs in the col that is the PHE col, and also is quantitative `cols {pheno_col: {isQuantitative, hasNA}}` should give us more info on expected behaviour and the possibility to catch errors.

**Comment by kousathanas** [comment]
for quantitative traits there is no need to test for missingness in the QC step.

**Comment by cgpu** [comment]
> for quantitative traits there is no need to test for missingness in the QC step.

Thanks @kousathanas  for verification, appreciate it!
